# -*- coding: utf-8 -*-
"""Swim Tracker Final

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t__UQ3Nq9zNAJsxu3L1K_uo813QdJTwB
"""

# Workout class stores workout details and formats a summary
class Workout:
  def __init__(self, date, distance, duration, wtype, rating, notes):
    self.date = date
    self.distance = distance
    self.duration = duration
    self.wtype = wtype
    self.rating = rating
    self.notes = notes

# Returns a clean workout summary
  def workout_summary(self):
    minutes = self.duration % 60
    hours = self.duration // 60

    if hours == 0:
      duration_text = (f"{minutes} minutes")

    elif hours > 0 and minutes == 0:
      duration_text = (f"{hours} hours ")

    else:
      duration_text = (f"{hours} hours {minutes} minutes ")

    summary = (f"--Workout Summary-- \n Date: {self.date} \n Distance: {self.distance} \n Duration: {duration_text} \n Workout type: {self.wtype} \n Rating: {self.rating} \n Notes: {self.notes}")
    return summary

# Goal class stores goal event + target time and formats a summary
class Goal:
  def __init__(self, event, target_time):
    self.event = event
    self.target_time = target_time

 # Returns formatted goal summary
  def goal_summary(self):
    minutes = self.target_time // 60
    seconds = self.target_time % 60
    time_text = (f"{minutes} minutes {seconds} seconds")

    summary = (f"--Goal Summary-- \n Event: {self.event} \n Target Time:  {time_text} (converted from {self.target_time} seconds)")
    return summary

# MeetResult stores meet times, optional comparisons, and summary output
class MeetResult:
  def __init__(self, date, event, seed_time, final_time, notes):
    self.date = date
    self.event = event
    self.seed_time = seed_time
    self.final_time = final_time
    self.notes = notes
    self.change_label = None
    self.change_amount = None
    self.goal_status = None


# Returns formatted meet summary
  def meet_results_summary(self):
    seed_minutes = self.seed_time // 60
    seed_seconds = self.seed_time % 60

    final_minutes = self.final_time // 60
    final_seconds = self.final_time % 60

    if seed_minutes == 0:
      seed_time_text = (f"{seed_seconds} seconds")

    elif seed_minutes > 0 and seed_seconds == 0:
      seed_time_text = (f"{seed_minutes} minutes")

    else:
      seed_time_text = (f"{seed_minutes} minutes {seed_seconds} seconds")


    if final_minutes == 0:
      final_time_text = (f"{final_seconds} seconds")

    elif final_minutes > 0 and final_seconds == 0:
      final_time_text = (f"{final_minutes} minutes")

    else:
      final_time_text = (f"{final_minutes} minutes {final_seconds} seconds")


    if self.change_label is None or self.change_amount is None:
      change_text = "Not calculated yet"

    else:
      change_text = (f"{self.change_label} {self.change_amount} seconds")


    if self.goal_status is None:
      goal_text = "No goal set yet"

    else:
      goal_text = (f"{self.goal_status}")


    summary = (f"--Meet Summary--\n Date: {self.date} \n Event: {self.event} \n Seed time: {seed_time_text} \n Final time: {final_time_text} \n Time change: {change_text} \n Goal check: {goal_text} \n Notes: {self.notes}")
    return summary


# Athlete stores workouts, meet results, and one goal
class Athlete:
  def __init__(self, name):
    self.name = name
    self.workouts = []
    self.meet_results = []
    self.goal = None

  def add_workout(self, workout):
    self.workouts.append(workout)

  def add_meet_result(self, meet_result):
    self.meet_results.append(meet_result)

  def set_goal(self, goal):
    self.goal = goal


# Helper class handles parsing, validation, and calculations
class Helper:
  @staticmethod
  # Converts H:MM or MM to minutes
  def parse_duration_to_minutes(time_str):
    if ":" in time_str:
      parts = time_str.split(":")
      hours = int(parts[0])
      minutes = int(parts[1])
      total_minutes = hours * 60 + minutes

    else:
      total_minutes = int(time_str)

    return total_minutes

  @staticmethod
  # Converts M:SS or SS to seconds
  def parse_time_to_seconds(time_str):
    if ":" in time_str:
      parts = time_str.split(":")
      minutes = int(parts[0])
      seconds = int(parts[1])
      total_seconds = minutes * 60 + seconds

    else:
      total_seconds = int(time_str)

    return total_seconds

  @staticmethod
  # Safe duration parsing
  def safe_parse_duration_to_minutes(time_str):
    try:
      return Helper.parse_duration_to_minutes(time_str)
    except:
      return None

  @staticmethod
  # Safe time parsing
  def safe_parse_time_to_seconds(time_str):
    try:
      return Helper.parse_time_to_seconds(time_str)
    except:
      return None


  @staticmethod
  # Safe integer parsing
  def safe_parse_int(value_str):
    try:
      return int(value_str)
    except:
      return None

  @staticmethod
  # Determines if final time is faster, slower, or equal
  def calculate_time_change(seed_time, final_time):
    if final_time < seed_time:
      label = "Faster by"
      amount = seed_time - final_time

    elif final_time > seed_time:
      label = "Slower by"
      amount = final_time - seed_time

    else:
      label = "No change"

      amount = 0

    return label, amount


  @staticmethod
  # Checks if a goal applies and whether it's met
  def determine_goal_status(goal, event, final_time):
    if goal is None:
      return "No goal set"

    if goal.event.lower().strip() != event.lower().strip():
      return "Goal is for a differnt event"

    if final_time <= goal.target_time:
      return "Goal met!"
    else:
      return "Goal not met yet"


# Main program menu
def Menu():
  print("--Swim Progress Tracker--\n")
  name = input("Enter your name: ")
  athlete = Athlete(name)

  while True:
    print()
    print("--Main Menu--")
    print("1. Log Workout")
    print("2. Log Meet Result")
    print("3. Set Goal")
    print("4. View Workouts")
    print("5. View Meet Results")
    print("6. View Goal")
    print("7. Exit")

    choice = input("Choice an option: ")
    print()

# Option 1: Log workout
    if choice == "1":
      date = input("Enter workout date (MM/DD/YYYY): ")

      while True:
       distance_str = input("Enter distance in yards: ")
       distance = Helper.safe_parse_int(distance_str)

       if distance is None or distance <= 0:
        print("Invalid distance. Please enter a number.")

       else:
         break

      while True:
       duration_str = input("Enter duration: ")
       duration = Helper.safe_parse_duration_to_minutes(duration_str)

       if duration is None or duration <= 0:
        print("Invalid duration. Please use H:MM or MM format and enter a positive time.")

       else:
        break


      wtype = input("Enter workout type (ex: Aerobic, Sprint, Technique , Recovery): ")

      while True:
       rating_str = input("Enter workout rating (1-5): ")
       rating = Helper.safe_parse_int(rating_str)

       if rating is None or rating < 1 or rating > 5:
        print("Invalid rating. Please enter a number between 1 and 5.")

       else:
        break



      notes = input("Enter any notes: ")

      workout = Workout(date, distance, duration, wtype, rating, notes)
      athlete.add_workout(workout)
      print("Workout logged:")
      print()
      print(workout.workout_summary())

 # Option 2: Log meet result
    elif choice == "2":
      date = input("Enter meet date (MM/DD/YYYY): ")
      event = input("Enter event (ex: 100 Free, 200 IM): ")


      while True:
       seed_str = input("Enter seed time (M:SS or SS): ")
       seed_time = Helper.safe_parse_time_to_seconds(seed_str)
       if seed_time is None or seed_time <= 0:
         print("Invalid seed time. Please use M:SS or SS format.")
       else:
          break


      while True:
       final_str = input("Enter final time (M:SS or SS): ")
       final_time = Helper.safe_parse_time_to_seconds(final_str)
       if final_time is None or final_time <= 0:
         print("Please enter final time. Use M:SS or SS format.")
       else:
        break


      notes = input("Enter any notes: ")

      meet = MeetResult(date, event, seed_time, final_time, notes)

# Add time change info (label + amount in seconds)
      label, amount = Helper.calculate_time_change(seed_time, final_time)
      meet.change_label = label
      meet.change_amount = amount

# Add time change info (label + amount in seconds)
      meet.goal_status = Helper.determine_goal_status(athlete.goal, event, final_time)

      athlete.add_meet_result(meet)
      print("Meet results logged: ")
      print()
      print(meet.meet_results_summary())

 # Option 3: Set goal
    elif choice == "3":
      event = input("Enter goal event (ex: 100 Free, 200 IM): ")

      while True:
       target_str = input("Enter target time (M:SS or SS): ")
       target_time = Helper.safe_parse_time_to_seconds(target_str)

       if target_time is None or target_time <= 0:
        print("Invalid target time. Please use M:SS or SS format.")
       else:
        break


      goal = Goal(event, target_time)
      athlete.set_goal(goal)
      print("Goal set:")
      print()
      print(goal.goal_summary())

  # Option 4: View workouts
    elif choice == "4":
      if not athlete.workouts:
        print("No workouts logged yet.")
      else:
        for w in athlete.workouts:
          print(w.workout_summary())

# Option 5: View meet results
    elif choice == "5":
      if not athlete.meet_results:
        print("No meet results logged yet.")
      else:
        for m in athlete.meet_results:
          print(m.meet_results_summary())

  # Option 6: View goal
    elif choice == "6":
      if athlete.goal is None:
        print("No goal set yet.")
      else:
        print(athlete.goal.goal_summary())

 # Option 7: Exit program
    elif choice == "7":
      break

# Invalid menu choice
    else:
      print("Invalid choice, Please enter a number from 1 to 7.")

# Run the program
Menu()